vars:
  stage: prod

components:
  terraform:
    vpc:
      metadata:
        component: vpc
        vars:
          name: use1-eks-region-failover
          cidr: 10.0.0.0/16
          azs:
            - us-east-1a
            - us-east-1b
          public_subnets:
            - 10.0.0.0/18
            - 10.0.64.0/18
          private_subnets:
            - 10.0.128.0/18
            - 10.0.192.0/18
